# Generated by Django 4.2.3 on 2023-08-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_user_author_remove_user_listings_bid_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='author',
            field=models.ForeignKey(default='root', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='author',
            field=models.ForeignKey(default='root', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
